### PR TITLE
TileView can now be placed into xml layout file

### PR DESCRIPTION
**Pull request by loentar**
Patch to fix TileView cannot be used in xml layout.

Related issue: #175

### CODE REVIEW

**Comment by moagrius** [comment]
Thanks for the PR - I'm happy to merge, but can you use the convention and style shown in stock Android (callbacks to `this`), e.g., http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.0_r1/android/widget/RelativeLayout.java#235

LMK if that doesn't make sense

**Comment by loentar** [comment]
It's ok, but I cannot create that constructor because super(..) require the API 21.

```
	public ZoomPanLayout( Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes ) {
		super(context, attrs, defStyleAttr, defStyleRes);
		sharedCtor(context);
	}
```

Shall I use reflection or just skip it?

**Comment by loentar** [comment]
For now I just strip out that constructor because I can't find any acceptable way to don't use reflection.

**Comment by moagrius** [comment]
Looks great, thanks!

**Comment by loentar** [comment]
Cool, thanks! Probably you need to update https://github.com/moagrius/TileView/wiki/FAQ ?

**Comment by moagrius** [comment]
yep, will do when i get a chance (or feel free, if you have the time and inclination)

**Pull request merged**
