### PR TITLE
Issue 285

### PR DESCRIPTION
**Pull request by AndrazP**
Added "-keepattributes EnclosingMethod" proguard rule that suppresses "Ignoring InnerClasses attribute for an anonymous inner class" warning.
Additionally updated gradle plugin and wrapper version, build tools version, compile sdk, target sdk and appcompact version to latest final version.

### CODE REVIEW

**Comment by peterLaurence** [comment]
Ok for proguard fix.
As for gradle update, wrapper and build tools update, @moagrius will decide on this. Although i also updated the version like you for my personal use, i just added those modifications to my git stash so i can go back and forth when i need to make a PR.

**Comment by moagrius** [comment]
i'm not comfortable upgrading gradle to 2.0 yet - we're still on 1.x at work since there were problems with plugins still lingering...  if you reduce this to just the proguard stuff, i'll merge.

thanks for contributing

**Comment by AndrazP** [comment]
Reverted the gradle update commit.

**Comment by moagrius** [comment]
Thank you!

**Comment by Bonan-Cao** [comment]
Thank you @AndrazP  I add "-keepattributes EnclosingMethod" in my proguard file, and it works. Thanks.

**Comment by histone** [comment]
Worked for me too :)

**Pull request merged**
