### PR TITLE
tile loading async

### PR DESCRIPTION
**Pull request by bnsantos**
I changed the way the tiles are loading, to user a thread pool. Also updated the disklrucache

### CODE REVIEW

**Comment by moagrius** [comment]
So after an very quick initial review, I like a lot of what you've done here; I'll have to dig into the thread stuff more to get a complete understanding, but one major issue is moving from min SDK of 8 to 15 - that's API 2.2 to API 4.0.3, which is a massively breaking change and there's no way I can merge that.  Can you achieve what you want to without changing the min SDK?  Also, try to keep with code style - I understand and appreciate the "m-" and "s-" prefixes, but since they're not used here, it wouldn't be appropriate - same with white space - you might have a completely justifiable reason for using the white space rules you do, but please conform to the existing set up.

**Comment by bnsantos** [comment]
Totally agree with you, was in a rush. Going to check those items over the weekend!

**Comment by moagrius** [comment]
Sounds good, looking forward to seeing the updates

**Comment by bnsantos** [comment]
So I checked the things I'm using for async loading tiles (ThreadPoolExecutor, BlockingQueue, Runnable) all of them are available since API 1. Also formatted the code to match the current pattern!
Another stuff I updated is using appcompact-v7 but I don't think this is also going to be any problem supporting api beginning 8. To make sure I run a quick test on an emulator api 8 and everything worked fine.

**Comment by moagrius** [comment]
Very cool - give me a few days to find some time to verify everything, but at first glance looks good

**Comment by moagrius** [comment]
So I've reviewed (but haven't actually run it), and in general it looks good.  Can you explain the benefits of the changes you're proposing?  I see the value in the caching changes ("working" is always better than "not working"), but AsyncTask uses a ThreadPool behind the scenes anyway, so I'm not sold on why you moved to explicit ThreadPoolExecutor instance, but could be convinced...  Could you enumerate each change and it's material benefit?

Also, if we do merge, this'd require a version change (in both manifest and gradle) to 1.0.15

**Comment by bnsantos** [comment]
Ok, I'll explain the issues I was facing using your lib before starting to work in a solution for that. Loading Tiles from s3 using BitmapDecoderHttp sometimes is too slow (especially on 3g here in Brazil). 

Why it is too slow the TileRenderTask (for line 36) was loading all Tiles that are visible in screen one at a time, so it would do a get request for one picture, download it, load it into to screen and the it will start the next Tile.

The solution I did was instead of using only one TileRenderTask to load ALL tiles I created one Runnable (TileDownloadRunner) to load one single Tile and using it with ThreadPoolExecutor android can handles multiples Runnables depending on the number of cores of the devices, also it could do some async stuff whenever I'm waiting for I/O operations it could load an already downloaded picture into screen which will looks more faster.

The main benefit was performance. Android uses ThreadPool behind the scenes but the current code was note creating multiple AsyncTasks to get the benefits of ThreadPool. I'm pretty sure I could dig into your code and find out a better solution using the same patterns you're using (AsyncTaks) to achieve the concurrent loading. But the solution I did was the fastest and simplest I could find right now.

**Comment by moagrius** [comment]
I get it - sounds great.  I'll run it locally some time this weekend as a final sanity check then, assuming all's well, merge.  Thanks for the update and the walkthrough - I really appreciate it.

**Comment by moagrius** [comment]
OK, I ran it, looks good - I've added you as a collaborator so you can merge yourself - a couple final requests for before/during merge:

1.  Could you update version to 1.0.15?
2.  Could you generate a JAR and add it to https://github.com/moagrius/TileView/releases?
3.  Could you push to maven and confirm availability?

LMK if you have any questions.

Thanks for contributing - very much appreciated.

**Comment by bnsantos** [comment]
Ok,

I'll do 1 and 2, not sure how to do 3. What about creating a tag for 1.0.15???

**Comment by bnsantos** [comment]
So the tag is created during the release process. It's just missing pushing jar to maven.

**Comment by moagrius** [comment]
Hm, another collaborator used to do that - I thought it was part of the gradle process, but I'll double check later - anyway, thanks very much for the awesome contribution

**Pull request merged**
