### PR TITLE
Fix #258 : optimize rendering task.

### LINKED ISSUE #258: Optimize rendering task
I am creating the issue discussed earlier, just to keep track of it.

Rendering task is given the list of visible tiles, without taking into account the tiles already rendered. In fact, they are but each time the TileRenderTask adds a tile to the view. This is particularly visible when using tiles from a network : when the visible area overlaps an area already rendered, all the tiles already rendered are decoded/downloaded again.

@moagrius 
```
LinkedList<Tile> getRenderList() {
  LinkedList<Tile> renderList = (LinkedList<Tile>) mTilesScheduledToRender.clone();
  renderList.removeAll( mTilesAlreadyRendered );
  return renderList;
}
```
The snippet you proposed works perfectly. I am just checking if there is anything more to modify.

### PR DESCRIPTION
**Pull request by peterLaurence**
I also renamed `mTilesScheduledToRender` to `mTilesVisible` as it was no longer the list of tiles scheduled to render.

Tested in the demo, it works as expected.

### CODE REVIEW

**Comment by moagrius** [comment]
awesome.  can you include a version bump?

**Comment by peterLaurence** [comment]
Ok i won't forget the next time.

**Comment by moagrius** [comment]
ah, sorry should have been more clear, we're on **2.0.10** (2.1.0 would indicate a major revision).

**Comment by peterLaurence** [comment]
np

**Comment by moagrius** [comment]
gah didn't see this get re-opened

+1, i'll merge when i get time to generate and push the artifacts to jcenter

**Comment by peterLaurence** [comment]
oups miss-click

**Comment by moagrius** [comment]
now available on jcenter

**Pull request merged**
