### PR TITLE
Explicitly Target JDK 8

### PR DESCRIPTION
**Pull request by MisterRager**
I'm having issues with both the post-JACK java 8 support and Robolectric with regard to TileView:

```
java.lang.VerifyError: Expecting a stackmap frame at branch target 49
Exception Details:
  Location:
    com/qozix/tileview/widgets/ZoomPanLayout.onTouchEvent(Landroid/view/MotionEvent;)Z @29: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 0021 2bb6 003c 3d2a b400 2c2b b600
    0x0000010: 433e 2ab4 0031 2bb6 0059 3604 1c9a 0014
    0x0000020: 1d9a 0010 1504 9a00 0b2a 2bb7 004a 9900
    0x0000030: 0704 a700 0403 ac                      


	at com.plangrid.android.DumbTest.ugh(DumbTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:487)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:143)
```

Telling proguard to target jdk 8 requires it to keep the stack map frames in the outputted class files so that stuff acting on the bytecode like the Google de-sugar tool or Robolectric don't come apart when verifying the lib.

### CODE REVIEW

**Comment by MisterRager** [comment]
The proguard file just pulls in the old rules from the default rules and drops the `-dontpreverify` statement to keep from changing too much.

**Comment by moagrius** [comment]
seems like a lot of changes to satisfy other build tools - is all that's needed really the `target 8` line?

**Comment by MisterRager** [comment]
Sorta - the other thing needed is not to call `-dontpreverify`

**Comment by moagrius** [comment]
Can you reduce the changes to just what's required?

**Comment by MisterRager** [comment]
That would mean dropping a lot of proguard rules that are brought in by default by the usual android proguard piece. If this is okay, I'll do that.

**Comment by moagrius** [comment]
yes please, only and exactly the changes required to meet the requirement

**Comment by MisterRager** [comment]
How is this?

**Comment by moagrius** [comment]
+1

**Comment by moagrius** [comment]
i'll get a release to jcenter soon

**Comment by MisterRager** [comment]
thanks!

**Pull request merged**
