### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by peterLaurence**
Fix misleading comment in the demo.
Fix typos in javadoc of DetailLevel.java

### CODE REVIEW

**Comment by peterLaurence** [comment]
Sorry for style change for the ```setTag( point );```
I saw that after doing the pull request. I keep that in mind for my next commit.

**Comment by moagrius** [comment]
if you fix the white space and push to master, this PR should reflect it...

**Comment by peterLaurence** [comment]
Done.

**Comment by moagrius** [comment]
Thank you!

**Pull request merged**
