### PR TITLE
Fix#252

### LINKED ISSUE #252: Sometimes, some tiles are not rendered
Hi,

Most of the time, tiles are correctly rendered. But sometimes, after an intense unzoom, some tiles are not rendered. At the beginning, i thought that my BitmapProvider was the culprit. Its implementation is very close to BitmapProviderAssets, because it looks for tiles located on the sd card. So i tried to log any Exception raised by BitmapFactory.decodeFile. But there were none.
At the moment, the only clue i have is that it happens just after a drop in memory usage of my app. I made a screen shot of that memory usage: 

screen

As a side note, even if some tiles are not rendered, if i want them appear, i just have to scroll (or zoom / unzoom) a little to trigger tiles painting.

### PR DESCRIPTION
**Pull request by peterLaurence**
This fixes #252, which is in fact the issue @chrisbrossard were having in #301 besides OOM. As you can see in #301, @chrisbrossard tested the changes and confirmed it fixes the issue. However it is hard to tell why this problem shows up now while i haven't seen it for a while.

In fact, i already made a PR for this. But it was never merged because it included other changes related to other issues. We already discussed the change made here, in #261, and you finally agreed the changes. 

Version bumped to 2.1.7

### CODE REVIEW

**Comment by peterLaurence** [comment]
Also, about the badge, i noticed that if we include this in readme.md :

https://img.shields.io/badge/TileView-2.1.7-blue.svg

it creates the badge on the fly. So all we have to do is to update the version number in the url. What do you think?

**Comment by moagrius** [comment]
re: PR, looks great, i remember it a bit, read up on it again, makes sense, +1.  i'll merge when i have a few minutes to generate artifacts.  do you want me to set you up on bintray so you can publish artifacts?

re: badge - i think the url you pasted is bad (it has the version number hardcoded in the URL)

thanks

**Comment by peterLaurence** [comment]
I will be available starting from tomorrow evening (so for you it is in about 20 hours). If you do it in the meantime, it's ok.

**Comment by moagrius** [comment]
I don't mind doing it, but do you want to be set up for releases in the future?

**Comment by peterLaurence** [comment]
Sure. When I make a PR and you are OK with it, this could speed things up if i can generate artifacts.

**Comment by moagrius** [comment]
cool.  do you have a https://bintray.com/ account (that's jcenter)?  if so, what's your user?  you can email me directly if you want (also, fwiw, you're free to email me directly any time).  i'll also post the gradle script i use to generate the aars...

**Comment by peterLaurence** [comment]
No don't have an account yet. I will create one tomorrow and I will email you.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by moagrius** [comment]
also, about the badge, the one i have in the readme auto-updates, i just forgot to draft a new release.  i just did so and it updated as expected.

anyway, ttyt

**Comment by peterLaurence** [comment]
I sent you an email at your address associated with your bintray account. Idk if you use the same for github.

**Comment by moagrius** [comment]
I got it, I'll try to get everything set up tonight

**Comment by moagrius** [comment]
i think my emails might be going in your spam...?

**Comment by peterLaurence** [comment]
Sorry, i completely forgot i didn't have notifications for this email address and haven't read your mail until now.
So i agree for merge and publish.

**Comment by peterLaurence** [comment]
I just made some tests again to double check. No issues. Let's merge..

**Pull request merged**
